// This is an autogenerated file from running `firebase genkit:new`. Do not edit.
'use server';

/**
 * @fileOverview AI-powered tagline suggestions for admin portfolio customization.
 *
 * This file defines a Genkit flow that suggests relevant taglines based on the admin's profile information.
 * It includes the `suggestTaglines` function, the `SuggestTaglinesInput` type, and the `SuggestTaglinesOutput` type.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const SuggestTaglinesInputSchema = z.object({
  name: z.string().describe('The name of the person.'),
  role: z.string().describe('The role of the person, e.g., Full Stack Developer.'),
  skills: z.string().describe('A comma-separated list of skills.'),
});
export type SuggestTaglinesInput = z.infer<typeof SuggestTaglinesInputSchema>;

const SuggestTaglinesOutputSchema = z.object({
  taglines: z.array(z.string()).describe('An array of suggested taglines.'),
});
export type SuggestTaglinesOutput = z.infer<typeof SuggestTaglinesOutputSchema>;

export async function suggestTaglines(input: SuggestTaglinesInput): Promise<SuggestTaglinesOutput> {
  return suggestTaglinesFlow(input);
}

const suggestTaglinesPrompt = ai.definePrompt({
  name: 'suggestTaglinesPrompt',
  input: {schema: SuggestTaglinesInputSchema},
  output: {schema: SuggestTaglinesOutputSchema},
  prompt: `You are an AI assistant specialized in generating creative and compelling taglines for personal portfolios.

  Given the following information, suggest 3 relevant taglines that highlight the person's expertise and aspirations.

  Name: {{{name}}}
  Role: {{{role}}}
  Skills: {{{skills}}}

  Taglines should be concise, engaging, and tailored to attract potential clients or employers.
  Return the taglines as a JSON array of strings.
  `,
});

const suggestTaglinesFlow = ai.defineFlow(
  {
    name: 'suggestTaglinesFlow',
    inputSchema: SuggestTaglinesInputSchema,
    outputSchema: SuggestTaglinesOutputSchema,
  },
  async input => {
    const {output} = await suggestTaglinesPrompt(input);
    return output!;
  }
);
